import type { Metadata } from "next";
import "@/app/globals.css";
import Footer from "@/_components/Footer/Footer";
import Navbar from "@/_components/layout/navbar/common/Navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <div className="min-h-screen">{children}</div>
      <Footer />
    </>
  );
}
