import type { Metadata } from "next";
import Footer from "@/_components/layout/Footer/Footer";
import Navbar from "@/_components/layout/navbar/common/Navbar";
import MobileWidget from "@/_components/layout/mobile-widget/MobileWidget";
import "@/styles/globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <div className="grow">{children}</div>
      <MobileWidget />
      <Footer />
    </div>
  );
}
